spring:
  datasource:
    url: jdbc:mysql://192.168.1.110:3306/buffer_id?useSSL=false
    auto-commit: true
    jdbc-url: jdbc:mysql://192.168.1.110:3306/buffer_id?useSSL=false
    username: root
    password: 123456
    minimum-idle: 1
    maximum-pool-size: 100
    idle-timeout: 300000
    max-lifetime: 1200000
  redis:
    host: 192.168.56.101
    password: 123456
